apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-creator-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - ingresses
  verbs:
  - create
  - delete
  - get
