apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      serviceAccountName: pod-creator-sa 
      containers:
      - name: frontend-app-container
        image: ashu0530/k8s-event-driven:v6
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ashutosh
          value: ashutosh 
