apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-rolebinding
subjects:
- kind: ServiceAccount
  name: pod-creator-sa
  namespace: ashutosh
roleRef:
  kind: ClusterRole
  name: pod-creator-role
  apiGroup: rbac.authorization.k8s.io
