apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: sa-manage-pods
  namespace: ashu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-pods
subjects:
- kind: ServiceAccount
  name: playground
  namespace: ashu
